use_frameworks!

platform :ios, '8.0'

target 'YHUIKit_Example' do
  pod 'YHUIKit', :path => '../'

  target 'YHUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
